### PR TITLE
feat: manualUpperCase

### PR DESCRIPTION
**Pull request by gdi2290**
String#toUpperCase doesn't produce correct results in browsers with Turkish locale, for this reason we need to detect this case and redefine toUpperCase method with correct but slower alternative.

### CODE REVIEW

**Comment by blakeembrey** [comment]
This can be a lot cleaner and suffers the issue that now Turkish users won't be able to upper case non-latin characters.

**Comment by blakeembrey** [comment]
Ok, I can't seem to find anything solid. Even https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLocaleUpperCase seems to agree, using `toUpperCase` should be ok.

**Comment by gdi2290** [comment]
perhaps using `toLocaleUpperCase` when available 

MDN:
>`toLocaleUpperCase()` does not affect the value of the string itself. In most cases, this will produce the same result as `toUpperCase()`, but for some locales, such as Turkish, whose case mappings do not follow the default case mappings in Unicode, there may be a different result.

**Comment by blakeembrey** [comment]
@gdi2290 Exactly, the phrasing of that indicates it'll work as expected. I really need to test this somehow though. If we want to support locales like Turkish, it should be a second parameter.

**Comment by blakeembrey** [comment]
@gdi2290 I can not for the life of me figure out how to get this to fail. I know it should, but I've changed the browser language, the system language and even downloaded the Turkish Firefox. Gah.

**Comment by blakeembrey** [comment]
Fixed with 8e426f1512f8b27e5cfc7f8af6ceb2fad6ef25e8

**Pull request closed without merging**
